In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
np.add(a,b)


array([ 7,  9, 11, 13, 15])

In [6]:
np.multiply(a,b)


array([ 6, 14, 24, 36, 50])

In [7]:

np.subtract(a,b)

array([-5, -5, -5, -5, -5])

In [8]:

np.divide(b,a)

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [9]:
x=np.divide(b,a)
np.around(x)

array([6., 4., 3., 2., 2.])

In [10]:
np.around(x,2)

array([6.  , 3.5 , 2.67, 2.25, 2.  ])

In [11]:
np.divmod(b,a)

(array([6, 3, 2, 2, 2], dtype=int32), array([0, 1, 2, 1, 0], dtype=int32))

In [12]:
np.trunc(x)

array([6., 3., 2., 2., 2.])

In [13]:
np.floor(x)

array([6., 3., 2., 2., 2.])

In [14]:
np.ceil(x)

array([6., 4., 3., 3., 2.])

In [16]:
np.log2(x)

array([2.5849625 , 1.80735492, 1.4150375 , 1.169925  , 1.        ])

In [19]:
np.prod([a,b])

3628800

In [20]:
np.prod([a,b],axis=1)

array([  120, 30240])

In [22]:
np.cumprod(a)

array([  1,   2,   6,  24, 120], dtype=int32)

In [23]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [24]:
np.sum([a,b])

55

In [25]:
np.sum([a,b],axis=1)

array([15, 40])

In [26]:
np.diff(a)

array([1, 1, 1, 1])

In [27]:
np.diff([a,b])

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.lcm(15,25)

75

In [29]:
np.gcd(15,25)

5

In [30]:
a1=np.array([10,15,20,50])
np.lcm.reduce(a)

60

In [31]:
np.lcm.reduce(a1)

300

In [32]:
np.sin(np.pi/2)

1.0

In [33]:
np.cos(np.pi/2)

6.123233995736766e-17

In [34]:
a2=np.array([0,np.pi/6,np.pi/4,np.pi/3,np.pi/2])
np.sin(a2)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [35]:
np.deg2rad(90)

1.5707963267948966

In [36]:
np.deg2rad(180)

3.141592653589793

In [37]:
np.rad2deg(np.pi/2)

90.0

In [38]:
np.hypot(12,5)


13.0

In [39]:
np.hypot(24,10)

26.0

In [42]:
a3=np.array([23,8,13,5,13,2,24,12])
np.unique(a3)

array([ 2,  5,  8, 12, 13, 23, 24])

In [44]:
a4=np.array([10,12,23,24,29])
np.intersectld(a3,a4)

AttributeError: module 'numpy' has no attribute 'intersectld'

In [45]:
np.setdiffld(a3,a4)

AttributeError: module 'numpy' has no attribute 'setdiffld'

In [46]:
np.setxorld(a3,a4)

AttributeError: module 'numpy' has no attribute 'setxorld'

In [47]:
np.NaN

nan